import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useSession} from 'next-auth/react'
import { Card, Button } from 'antd';
import { Try } from '../components/Try'

const Home: NextPage = () => {

  const session = useSession();
  console.log({session});
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button type="primary">Primary Button</Button>
      <Card
    hoverable
    style={{ width: 240 }}
    cover={<img alt="example" src="https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png" />}
  >
  </Card>
  <Try/>
    </div>
  )
}

export default Home
